
version: 2.0
jobs:
  build:
    dockerize:
      machine: true
      steps:
        - checkout
        #login to docker
        - run: docker login -u nabadoon -p Shadia12#
        #Build the application image
        - run: docker buid -t nabadoon/myapplication:$CIRCLE_SHA1 .
        #deploy the image
        - run: docker push nabadoon/myapp:$CIRCLE_SHA1
